project:
  type: website

website:
  title: "Kalle Bylin"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  google-analytics: "G-L4ML23KDLF"
format:
  html:
    theme: zephyr
    css: styles.css
execute:
  freeze: auto
